import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				{/* <OnMetaWidget
					config={{
						apiKey: "",
						fiatAmount: 100,
						tokenAddress: "0xeeeeeeeeeeeeeeeeeeeeee",
						walletAddress: "0xExmapleWalletAdress",
					}}
				/> */}
			</body>
		</html>
	);
}
